baseURL: "https://abhinjata.github.io/graphmylifeonhugo/" 
title: Graph My Life
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Articles
          url: articles/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "HI."
    author: Abhinav Jata
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["articles","portfolio","papers","data"]
    ShowToc: false
    disableScrollToTop: false
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: true
    math: true
    profileMode:
          enabled: true
          title: Abhinav Jata
          subtitle: "Hi."
          imageUrl: "1c11fb41fe5e8057f2eba1fcdb547646.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Articles
              url: articles/
            - name: Papers
              url: papers/
            - name: Data
              url: data/
            - name: Portfolio
              url: portfolio/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            - name: Blog
              url: https://lifeislikethemeyerscurve.wordpress.com/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:abhinav.jata.986@gmail.com
        - name: GitHub
          url: https://github.com/abhinjata
        - name: Twitter
          url: https://x.com/letsgraphmylife

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Graph My Life"
      icon: favicon.png
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
